name = "Reading List"
license = "MIT"
licenselink = "https://github.com/michaelvigor/hugo-theme-reading-list/blob/master/LICENSE.md"
description = "Minimal theme for self hosted Pocket. Fork of Slim theme (https://github.com/zhe/hugo-theme-slim)"
homepage = "https://github.com/michaelvigor/hugo-theme-reading-list"
tags = ["minimal", "clean", "neat", "black white", "blog"]
min_version = 0.13

[author]
    name = "Michael Vigor"
    homepage = "https://michaelvigor.dev"
